[package]
name = "wasm-to-rust"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
parity-wasm = "0.27.2"
structopt = "0.2.5"
unicode-xid = "0.1.0"
unidecode = "0.3.0"